### ISSUE TITLE
Emit error on multiple package versions of the same module

### ISSUE THREAD

**Issue by 5ebastianMeier** [5minds/minstall#2]
The framework should exit with an error if it recognizes multiple versions of the same package used as a dependency throughout the entire application.

The error should list all modules that have the package in question as a dependency as well as the version each package expects.

**Comment by heikomat** [comment]
@5ebastianMeier Because minstall gets called recursevly, it's not possible to show all version mismatches at once. But when such an error occurs, the error message tells you what module minstall was trying to install, what dependency failed, which package version of that dependency he found, and which version-range was requested by the module.

Because it's a postinstall script, fixing wrong versions should be fast enough, because 'npm install' won't have to reinstall everything every time

**Comment by heikomat** [comment]
As of version 1.3.0, having conflicting dependencies is no longer an issue, because minstall can handle/install them correctly, though it still gives a hint, that one might try to use the same package-versions throughout the whole project.

If this is a suitable solution for your problem, and if 1.3.0 is supposed to be merged into this fork, this issue can be closed @5ebastianMeier
